<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="9" hostname="COL-TNUZUM" failures="1" tests="1" name="Default test" time="22.034" errors="0" timestamp="16 Aug 2019 16:05:27 GMT">
  <testcase classname="EME.PageLaunchTest" name="ScheduleApptsButtonTest" time="12.033">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at resources.reusableMethods.catchErrorMessage(reusableMethods.java:129)
at EME.PageLaunchTest.ScheduleApptsButtonTest(PageLaunchTest.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ScheduleApptsButtonTest -->
  <testcase classname="EME.PageLaunchTest" name="EditMyInfoButtonTest" time="0.0">
    <ignored/>
  </testcase> <!-- EditMyInfoButtonTest -->
  <testcase classname="EME.PageLaunchTest" name="ManageFamilyButtonTest" time="0.0">
    <ignored/>
  </testcase> <!-- ManageFamilyButtonTest -->
  <testcase classname="EME.PageLaunchTest" name="ScheduleClassesButtonTest" time="0.0">
    <ignored/>
  </testcase> <!-- ScheduleClassesButtonTest -->
  <testcase classname="EME.PageLaunchTest" name="ForgotUsernameButtonTest" time="0.0">
    <ignored/>
  </testcase> <!-- ForgotUsernameButtonTest -->
  <testcase classname="EME.PageLaunchTest" name="PayNowButtonTest" time="0.0">
    <ignored/>
  </testcase> <!-- PayNowButtonTest -->
  <testcase classname="EME.PageLaunchTest" name="MyPackagesButtonTest" time="0.0">
    <ignored/>
  </testcase> <!-- MyPackagesButtonTest -->
  <testcase classname="EME.PageLaunchTest" name="ForgotPasswordButtonTest" time="0.0">
    <ignored/>
  </testcase> <!-- ForgotPasswordButtonTest -->
  <testcase classname="EME.PageLaunchTest" name="AcctHistoryButtonTest" time="0.0">
    <ignored/>
  </testcase> <!-- AcctHistoryButtonTest -->
  <testcase classname="EME.PageLaunchTest" name="CartButtonTest" time="0.0">
    <ignored/>
  </testcase> <!-- CartButtonTest -->
</testsuite> <!-- Default test -->
